title: Sorbonne University Bolide Manuals
description: Consider this the bible for the two cars. Please update this regularly.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Nicolas Hammje
repo_url: "https://github.com/SorbonneUniversityBolideContributors/Course_2025"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
